Watching for file changes with StatReloader
/Users/erikna/Documents/development/challenge/src/config/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/erikna/Documents/development/challenge/src/config/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/erikna/Documents/development/challenge/src/web/views/stocks.py changed, reloading.
Watching for file changes with StatReloader
/Users/erikna/Documents/development/challenge/src/web/views/stock_charts.py changed, reloading.
Watching for file changes with StatReloader
/Users/erikna/Documents/development/challenge/src/web/views/user_stocks.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 107912
Internal Server Error: /stock-chart/
Traceback (most recent call last):
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 126, in _wrapper_view
    result = middleware.process_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/middleware/cache.py", line 153, in process_request
    if request.method not in ("GET", "HEAD"):
       ^^^^^^^^^^^^^^
AttributeError: 'StockChartsView' object has no attribute 'method'
"GET /stock-chart/ HTTP/1.1" 500 78624
"GET / HTTP/1.1" 200 107912
Internal Server Error: /user-stocks/
Traceback (most recent call last):
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 126, in _wrapper_view
    result = middleware.process_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/middleware/cache.py", line 153, in process_request
    if request.method not in ("GET", "HEAD"):
       ^^^^^^^^^^^^^^
AttributeError: 'HomeView' object has no attribute 'method'
"GET /user-stocks/ HTTP/1.1" 500 88660
Internal Server Error: /user-stocks/
Traceback (most recent call last):
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 126, in _wrapper_view
    result = middleware.process_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/middleware/cache.py", line 153, in process_request
    if request.method not in ("GET", "HEAD"):
       ^^^^^^^^^^^^^^
AttributeError: 'HomeView' object has no attribute 'method'
"GET /user-stocks/ HTTP/1.1" 500 88660
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 107912
/Users/erikna/Documents/development/challenge/src/data_fetcher/tasks/tasks.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /stock-chart/
Traceback (most recent call last):
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 126, in _wrapper_view
    result = middleware.process_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/middleware/cache.py", line 153, in process_request
    if request.method not in ("GET", "HEAD"):
       ^^^^^^^^^^^^^^
AttributeError: 'StockChartsView' object has no attribute 'method'
"GET /stock-chart/ HTTP/1.1" 500 78624
/Users/erikna/Documents/development/challenge/src/web/views/stock_charts.py changed, reloading.
Watching for file changes with StatReloader
"GET /stock-chart/ HTTP/1.1" 200 3607210
"GET / HTTP/1.1" 200 107912
Internal Server Error: /user-stocks/
Traceback (most recent call last):
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 126, in _wrapper_view
    result = middleware.process_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/middleware/cache.py", line 153, in process_request
    if request.method not in ("GET", "HEAD"):
       ^^^^^^^^^^^^^^
AttributeError: 'HomeView' object has no attribute 'method'
"GET /user-stocks/ HTTP/1.1" 500 88660
/Users/erikna/Documents/development/challenge/src/web/views/stock_charts.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 107912
Internal Server Error: /user-stocks/
Traceback (most recent call last):
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 126, in _wrapper_view
    result = middleware.process_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/middleware/cache.py", line 153, in process_request
    if request.method not in ("GET", "HEAD"):
       ^^^^^^^^^^^^^^
AttributeError: 'HomeView' object has no attribute 'method'
"GET /user-stocks/ HTTP/1.1" 500 88660
"GET / HTTP/1.1" 200 107912
Internal Server Error: /stock-chart/
Traceback (most recent call last):
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 126, in _wrapper_view
    result = middleware.process_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/middleware/cache.py", line 153, in process_request
    if request.method not in ("GET", "HEAD"):
       ^^^^^^^^^^^^^^
AttributeError: 'StockChartsView' object has no attribute 'method'
"GET /stock-chart/ HTTP/1.1" 500 78624
/Users/erikna/Documents/development/challenge/src/web/views/stock_charts.py changed, reloading.
Watching for file changes with StatReloader
"GET /stock-chart/ HTTP/1.1" 200 3607210
- Broken pipe from ('127.0.0.1', 64541)
/Users/erikna/Documents/development/challenge/src/web/views/user_stocks.py changed, reloading.
Watching for file changes with StatReloader
- Broken pipe from ('127.0.0.1', 64547)
"GET /stock-chart/ HTTP/1.1" 200 3607210
"GET /user-stocks/ HTTP/1.1" 200 11156
"GET / HTTP/1.1" 200 107912
- Broken pipe from ('127.0.0.1', 64548)
"GET /user-stocks/ HTTP/1.1" 200 11156
"GET /stock-chart/ HTTP/1.1" 200 3607210
"GET /stock-chart/ HTTP/1.1" 200 3607210
"GET /stock-chart/ HTTP/1.1" 200 3607210
"GET /stock-chart/ HTTP/1.1" 200 3607210
"GET /stock-chart/ HTTP/1.1" 200 3607210
"GET /stock-chart/ HTTP/1.1" 200 3607210
"GET /stock-chart/ HTTP/1.1" 200 3607210
/Users/erikna/Documents/development/challenge/src/web/views/stock_charts.py changed, reloading.
Watching for file changes with StatReloader
"GET /stock-chart/ HTTP/1.1" 200 3607200
"GET /stock-chart/ HTTP/1.1" 200 3620358
Watching for file changes with StatReloader
"GET /stock-chart/ HTTP/1.1" 200 3620358
"GET /stock-chart/ HTTP/1.1" 200 3620339
"GET /static/fa/css/all.min.css HTTP/1.1" 200 102025
"GET /static/favicon.ico HTTP/1.1" 200 15406
"GET /stock-chart/ HTTP/1.1" 200 3620331
"GET /stock-chart/ HTTP/1.1" 200 3620326
"GET /stock-chart/ HTTP/1.1" 200 3620387
"GET /stock-chart/ HTTP/1.1" 200 3620365
"GET /stock-chart/ HTTP/1.1" 200 3620386
"GET /stock-chart/ HTTP/1.1" 200 3620386
"GET /stock-chart HTTP/1.1" 301 0
"GET /stock-chart/ HTTP/1.1" 200 3620386
"GET / HTTP/1.1" 200 107930
Not Found: /login
"GET /login HTTP/1.1" 404 3221
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3239
/Users/erikna/Documents/development/challenge/src/web/views/stock_charts.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 107939
"GET /accounts/login HTTP/1.1" 301 0
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 25, in _wrapper_view
    resolved_login_url = resolve_url(login_url or settings.LOGIN_URL)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/functional.py", line 149, in __wrapper__
    res = func(*self.__args, **self.__kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"GET /accounts/login/ HTTP/1.1" 500 89836
/Users/erikna/Documents/development/challenge/src/web/views/login.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 25, in _wrapper_view
    resolved_login_url = resolve_url(login_url or settings.LOGIN_URL)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/functional.py", line 149, in __wrapper__
    res = func(*self.__args, **self.__kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'accounts/login' not found. 'accounts/login' is not a valid view function or pattern name.
"GET /accounts/login/ HTTP/1.1" 500 89998
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 107949
- Broken pipe from ('127.0.0.1', 65519)
"GET /stock-chart/ HTTP/1.1" 200 3620405
"GET /stock-chart/?symbol=B3SA&interval=1m HTTP/1.1" 200 3594059
"GET /user-stocks/ HTTP/1.1" 200 11193
"DELETE /user-stocks/delete/2/ HTTP/1.1" 200 55
"GET /user-stocks/ HTTP/1.1" 200 11193
Not Found: /user-stocks/delete/2/
"DELETE /user-stocks/delete/2/ HTTP/1.1" 404 3452
"DELETE /user-stocks/delete/3/ HTTP/1.1" 200 55
"GET /user-stocks/ HTTP/1.1" 200 11193
"GET /user-stocks/ HTTP/1.1" 200 11193
"GET /user-stocks/ HTTP/1.1" 200 11193
"GET /user-stocks/ HTTP/1.1" 200 11193
/Users/erikna/Documents/development/challenge/src/web/views/user_stocks.py changed, reloading.
Watching for file changes with StatReloader
"GET /user-stocks/ HTTP/1.1" 200 10564
"GET /static/img/empty_stocks.svg HTTP/1.1" 304 0
"GET /user-stocks/ HTTP/1.1" 200 10489
"GET / HTTP/1.1" 200 107949
"GET / HTTP/1.1" 200 107949
Not Found: /stock_data/ABEV/1m
"GET /stock_data/ABEV/1m HTTP/1.1" 404 3260
Not Found: /stock_data/ABEV/1m
"GET /stock_data/ABEV/1m HTTP/1.1" 404 3260
Not Found: /stock_data/ASAI/1m
"GET /stock_data/ASAI/1m HTTP/1.1" 404 3260
Not Found: /stock_data/ASAI/1m
"GET /stock_data/ASAI/1m HTTP/1.1" 404 3260
Not Found: /stock_data/ABEV/1m
"GET /stock_data/ABEV/1m HTTP/1.1" 404 3260
Not Found: /stock_data/ABEV/1m
"GET /stock_data/ABEV/1m HTTP/1.1" 404 3260
Not Found: /stock_data/ABEV/1m
"GET /stock_data/ABEV/1m HTTP/1.1" 404 3260
/Users/erikna/Documents/development/challenge/src/web/views/stocks.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 107949
Not Found: /stock_data/ABEV/1m
"GET /stock_data/ABEV/1m HTTP/1.1" 404 3260
Not Found: /stock_data/ABEV/1m
"GET /stock_data/ABEV/1m HTTP/1.1" 404 3260
/Users/erikna/Documents/development/challenge/src/web/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 107949
"GET /stock_data/ABEV/1m HTTP/1.1" 200 118259
"GET /stock_data/ABEV/1m HTTP/1.1" 200 118259
"GET /stock_data/ABEV/5m HTTP/1.1" 200 12041
"GET /stock_data/ABEV/5m HTTP/1.1" 200 12041
"GET /stock_data/ABEV/5m HTTP/1.1" 200 12041
"GET /stock_data/ABEV/5m HTTP/1.1" 200 12041
"GET / HTTP/1.1" 200 107939
"GET /stock_data/ABEV/1m HTTP/1.1" 200 118259
"GET /stock_data/ABEV/1m HTTP/1.1" 200 118259
"GET /stock_data/ABEV/5m HTTP/1.1" 200 12041
"GET /stock_data/ABEV/5m HTTP/1.1" 200 12041
"GET /stock_data/ABEV/5m HTTP/1.1" 200 12041
"GET /stock_data/ABEV/5m HTTP/1.1" 200 12041
"GET /stock_data/ABEV/5m HTTP/1.1" 200 12041
"GET /stock_data/ABEV/5m HTTP/1.1" 200 12041
/Users/erikna/Documents/development/challenge/src/web/views/stocks.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 107939
"GET / HTTP/1.1" 200 107949
Internal Server Error: /stock_data/ABEV/5m
Traceback (most recent call last):
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 126, in _wrapper_view
    result = middleware.process_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/middleware/cache.py", line 153, in process_request
    if request.method not in ("GET", "HEAD"):
       ^^^^^^^^^^^^^^
AttributeError: 'StockDataView' object has no attribute 'method'
"GET /stock_data/ABEV/5m HTTP/1.1" 500 78704
Internal Server Error: /stock_data/ABEV/5m
Traceback (most recent call last):
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 126, in _wrapper_view
    result = middleware.process_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/middleware/cache.py", line 153, in process_request
    if request.method not in ("GET", "HEAD"):
       ^^^^^^^^^^^^^^
AttributeError: 'StockDataView' object has no attribute 'method'
"GET /stock_data/ABEV/5m HTTP/1.1" 500 78704
Internal Server Error: /stock_data/ABEV/1m
Traceback (most recent call last):
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 126, in _wrapper_view
    result = middleware.process_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/middleware/cache.py", line 153, in process_request
    if request.method not in ("GET", "HEAD"):
       ^^^^^^^^^^^^^^
AttributeError: 'StockDataView' object has no attribute 'method'
"GET /stock_data/ABEV/1m HTTP/1.1" 500 78704
Internal Server Error: /stock_data/ABEV/1m
Traceback (most recent call last):
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 126, in _wrapper_view
    result = middleware.process_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/middleware/cache.py", line 153, in process_request
    if request.method not in ("GET", "HEAD"):
       ^^^^^^^^^^^^^^
AttributeError: 'StockDataView' object has no attribute 'method'
"GET /stock_data/ABEV/1m HTTP/1.1" 500 78704
/Users/erikna/Documents/development/challenge/src/web/views/stocks.py changed, reloading.
Watching for file changes with StatReloader
/Users/erikna/Documents/development/challenge/src/web/views/stocks.py changed, reloading.
Watching for file changes with StatReloader
/Users/erikna/Documents/development/challenge/src/web/views/user_stocks.py changed, reloading.
Watching for file changes with StatReloader
/Users/erikna/Documents/development/challenge/src/data_fetcher/tasks/tasks.py changed, reloading.
Watching for file changes with StatReloader
/Users/erikna/Documents/development/challenge/src/data_fetcher/tasks/tasks.py changed, reloading.
Watching for file changes with StatReloader
/Users/erikna/Documents/development/challenge/src/data_fetcher/tasks/tasks.py changed, reloading.
Watching for file changes with StatReloader
/Users/erikna/Documents/development/challenge/src/data_fetcher/tasks/tasks.py changed, reloading.
Watching for file changes with StatReloader
/Users/erikna/Documents/development/challenge/src/data_fetcher/tasks/tasks.py changed, reloading.
Watching for file changes with StatReloader
"GET /stock_data/ASAI/1m HTTP/1.1" 200 112803
"GET /stock_data/ASAI/1m HTTP/1.1" 200 112803
"GET /stock_data/ASAI/1m HTTP/1.1" 200 112803
"GET /stock_data/ASAI/1m HTTP/1.1" 200 112803
"GET /stock_data/CPFE/1m HTTP/1.1" 200 2
"GET /stock_data/CPFE/1m HTTP/1.1" 200 2
"GET /stock_data/COGN/1m HTTP/1.1" 200 2
"GET /stock_data/COGN/1m HTTP/1.1" 200 2
"GET /stock_data/CMIG/1m HTTP/1.1" 200 2
"GET /stock_data/CMIG/1m HTTP/1.1" 200 2
"GET /stock_data/CIEL/1m HTTP/1.1" 200 2
"GET /stock_data/CIEL/1m HTTP/1.1" 200 2
"GET /stock_data/CSNA/1m HTTP/1.1" 200 2
"GET /stock_data/CSAN/1m HTTP/1.1" 200 2
"GET /stock_data/CRFB/1m HTTP/1.1" 200 2
"GET /stock_data/CPLE/1m HTTP/1.1" 200 2
"GET /stock_data/EGIE/1m HTTP/1.1" 200 2
"GET /stock_data/GOLL/1m HTTP/1.1" 200 2
"GET /stock_data/AZUL/1m HTTP/1.1" 200 111603
"GET /stock_data/AZUL/1m HTTP/1.1" 200 111603
"GET /stock_data/B3SA/1m HTTP/1.1" 200 2
"GET /stock_data/B3SA/1m HTTP/1.1" 200 2
"GET /stock_data/AZUL/5m HTTP/1.1" 200 22894
"GET /stock_data/AZUL/5m HTTP/1.1" 200 22894
"GET /stock_data/B3SA/5m HTTP/1.1" 200 2
"GET /stock_data/B3SA/5m HTTP/1.1" 200 2
"GET /stock_data/AZUL/5m HTTP/1.1" 200 22894
"GET /stock_data/AZUL/5m HTTP/1.1" 200 22894
"GET /stock_data/B3SA/5m HTTP/1.1" 200 2
"GET /stock_data/B3SA/5m HTTP/1.1" 200 2
"GET / HTTP/1.1" 200 107939
"GET /static/fa/css/all.min.css HTTP/1.1" 200 102025
"GET /static/favicon.ico HTTP/1.1" 200 15406
"GET /accounts/login HTTP/1.1" 301 0
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 25, in _wrapper_view
    resolved_login_url = resolve_url(login_url or settings.LOGIN_URL)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/utils/functional.py", line 149, in __wrapper__
    res = func(*self.__args, **self.__kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erikna/Documents/development/challenge/env/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'accounts/login' not found. 'accounts/login' is not a valid view function or pattern name.
"GET /accounts/login/ HTTP/1.1" 500 89998
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3240
/Users/erikna/Documents/development/challenge/src/web/views/login.py changed, reloading.
Watching for file changes with StatReloader
"GET /accounts/login/ HTTP/1.1" 200 3388
"GET /accounts/login/ HTTP/1.1" 200 3377
"GET /accounts/login/ HTTP/1.1" 200 3344
"GET /accounts/login/ HTTP/1.1" 200 3355
"GET /accounts/login/ HTTP/1.1" 200 3360
"GET /accounts/login/ HTTP/1.1" 200 3360
"GET /accounts/login/ HTTP/1.1" 200 3365
"GET /accounts/login/ HTTP/1.1" 200 3370
"GET /accounts/login/ HTTP/1.1" 200 3380
/Users/erikna/Documents/development/challenge/src/web/views/login.py changed, reloading.
Watching for file changes with StatReloader
"GET /accounts/login/ HTTP/1.1" 200 3380
"POST /accounts/login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 107949
"GET /accounts/login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 107949
/Users/erikna/Documents/development/challenge/src/data_fetcher/tasks/tasks.py changed, reloading.
Watching for file changes with StatReloader
